### ISSUE TITLE
Child is draggable to

### ISSUE THREAD

**Issue by sonalys** [JulianG/react-list-drag-and-drop#5]
if i put a text input inside this draggable list, i'm not able to select the text inside, nor move the pointer using the mouse

**Comment by JulianG** [comment]
Hi @raicon 

I'm afraid you are correct.

In [RLDDItemComponent.tsx#L88](https://github.com/JulianG/react-list-drag-and-drop/blob/master/src/RLDDItemComponent.tsx#L88) we're calling `event.preventDefault();`.
But if we simply remove this, then there are some side effects.

Unfortunately I don't have time to properly  fix it right now.

Would you like to try and make a PR?

**Comment by raicon** [comment]
Should create 2 components, 1 responsible for drag management and another
for being draggable, simplest solution.

Em qui, 18 de abr de 2019 12:58, Julian <notifications@github.com> escreveu:
